<?php echo $this->doctype(); ?>

<html lang="en">
 

<style type="text/css">
body {
    background-color: #CCC;
    margin:80px 80px 100px 100px;
}

#fixedheader {
    position:fixed;
    top:0px;
    left:0px;
    width:100%;
    color:white;
    background:#333;
    padding:20px;
    margin-right: 
}

#fixedfooter {
    position:fixed;
    bottom:0px;
    left:0px;
    width:100%;
    color:#CCC;
    background:#333;
    padding:8px;
}

#fixedheader a {
    list-style-type: none;
    color: white;
    padding: 20px;
}
</style>
    <body>
        <div id="fixedheader">
        </div>
        
       
        <div class="container" style="margin-left:10px">
            <?php echo $this->content; ?>
           
        </div> <!-- /container -->
        <div id="fixedfooter">Bottom div content</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
